FoodBankManage/urls.py
from django.urls import path
from FoodBankManage import views

# SET THE NAMESPACE!
app_name = 'FoodBankManage'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('foodBankBeneficiary/',views.foodBankBeneficiary,name='foodBankBeneficiary'),
    path('foodBankInventory/',views.foodBankInventory,name='foodBankInventory'),
    path('user_login/',views.user_login,name='user_login'),
    path('Blockname/',views.Blockname,name='Blockname'),
    path('Blockname2/',views.Blockname2,name='Blockname2'),
    path('foodBankAdd/',views.foodBankAdd,name='foodBankAdd'),
    path('foodBankInventrydryAdd/',views.foodBankInventrydryAdd,name='foodBankInventrydryAdd'),
    path('foodBankInventrymidAdd/',views.foodBankInventrymidAdd,name='foodBankInventrymidAdd'),
    path('foodBankInventrycookAdd/',views.foodBankInventrycookAdd,name='foodBankInventrycookAdd'),
]

Foodbank/urls.py
from django.contrib import admin
from django.urls import path,include
from FoodBankManage import views

urlpatterns = [
    path('',views.index,name='index'),
    path('special/',views.special,name='special'),
    path('admin/', admin.site.urls),
    path('FoodBankManage/',include('FoodBankManage.urls')),
    path('logout/', views.user_logout, name='logout'),
]

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Food Bank NIC</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          {# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">Food Bank</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          

          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
          <li><a href="{% url 'FoodBankManage:Blockname' %}">Food Bank Beneficiary</a></li>
          <li><a href="{% url 'FoodBankManage:Blockname2' %}">Food Bank Inventory</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'FoodBankManage:user_login' %}">Login</a></li>
          {% endif %}
          
        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>

    <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

templates/block.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<link rel="stylesheet" href="{% static 'style.css'%}">
  <div class="container">
    <div class="jumbotron">

      {% if user.is_authenticated %}
      <h2>Food Bank Beneficiaries</h2>
    {% else %}
    <h1>Please Login</h1>

    <form method="post" action="{% url 'FoodBankManage:user_login' %}">
      {% csrf_token %}
      
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Username">

      <label for="password"></label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">

    </form>

    {% endif %}

      
    </div>

    {% if user.is_authenticated %}
    <div class="contai">  
        <form id="contact" action="../foodBankBeneficiary/" name="block" method="POST">
            {% csrf_token %}
            <fieldset>
                <select name="block_name" id="block">
                    <option value="">Block</option>
                    {% for i in blocks %}
                    <option value="{{ i }}">{{ i }}</option>
                    {% endfor %}
                </select>
            </fieldset>
          <fieldset>
            <button name="submit" value="Next" type="submit" id="contact-submit">Next</button>
          </fieldset>
          
        </form>
      </div>

    {% endif %}
  </div>

  
{% endblock %}

templates/block2.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<link rel="stylesheet" href="{% static 'style.css'%}">
  <div class="container">
    <div class="jumbotron">

      {% if user.is_authenticated %}
      <h2>Food Bank Beneficiaries</h2>
    {% else %}
    <h1>Please Login</h1>

    <form method="post" action="{% url 'FoodBankManage:user_login' %}">
      {% csrf_token %}
      
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Username">

      <label for="password"></label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">

    </form>

    {% endif %}

      
    </div>

    {% if user.is_authenticated %}
    <div class="contai">  
        <form id="contact" action="../foodBankInventory/" name="block" method="POST">
            {% csrf_token %}
            <fieldset>
                <select name="block_name" id="block">
                    <option value="">Block</option>
                    {% for i in blocks %}
                    <option value="{{ i }}">{{ i }}</option>
                    {% endfor %}
                </select>
            </fieldset>
            <fieldset>
              <select name="inventry" id="block">
                  <option value="dryfoodpacket">Dry Food Packet</option>
                  <option value="middaymeal">Mid Day Meal</option>
                  <option value="cookedmeal">Cooked Meal</option>
              </select>
          </fieldset>
          <fieldset>
            <button name="submit" value="Next" type="submit" id="contact-submit">Next</button>
          </fieldset>
          
        </form>
      </div>

    {% endif %}
  </div>

  
{% endblock %}

templates/foodbeneficiary.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<link rel="stylesheet" href="{% static 'style.css'%}">
  <div class="container">
    <div class="jumbotron">

      {% if user.is_authenticated %}
      <h2>Food Bank Beneficiaries</h2>
    {% else %}
    <h1>Please Login</h1>

    <form method="post" action="{% url 'FoodBankManage:user_login' %}">
      {% csrf_token %}
      
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Username">

      <label for="password"></label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">

    </form>

    {% endif %}

      
    </div>

    {% if user.is_authenticated %}
    <div class="contai">  
        <form id="contact" name="beneficiary" action="../foodBankAdd/" method="POST">
          {% csrf_token %}
            <fieldset>
              <select name="block_name" id="block" >
                    <option value="{{ blocke }}">{{ blocke }}</option>
                </select>
            </fieldset>
            <fieldset>
                <select name="gram" id="gram">
                    <option value="">Gram Panchayat</option>
                    {% for gram in pancha %}
                    <option value="{{ gram }}">{{ gram }}</option>
                    {% endfor %}
                </select>
            </fieldset>
            <fieldset>
                <input placeholder="Head Of Family (Name)" name="head" type="text" tabindex="1" required autofocus>
            </fieldset>
          <fieldset>
            <input placeholder="Total Members In Family" name="members" type="text" tabindex="1" required autofocus>
          </fieldset>
          <fieldset>
            <input placeholder="Mobile" type="text" name="mobile" tabindex="2" required>
          </fieldset>
          <fieldset>
            <p>NFSA</p>
            <input type="radio" id="yes" name="NFSA" value="1">
            <label for="yes">Yes</label><br>
            <input type="radio" id="no" name="NFSA" value="0">
            <label for="no">No</label><br>
          </fieldset>
          <fieldset>
            <input placeholder="Food Packet (Count)" name="foodpacket" type="text" tabindex="4" required>
          </fieldset>
          <fieldset>
            <input placeholder="Wheat (In Kg)" name="wheat" type="text" tabindex="5" required>
          </fieldset>
          <fieldset>
            <input placeholder="Rice (In Kg)" name="rice" type="text" tabindex="6" required>
          </fieldset>
          <fieldset>
            <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
          </fieldset>
          
        </form>
      </div>

    {% endif %}
  </div>

  
{% endblock %}

templates/foodinventrycook.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<link rel="stylesheet" href="{% static 'style.css'%}">
  <div class="container">
    <div class="jumbotron">

      {% if user.is_authenticated %}
      <h2>Food Bank Inventory</h2>
      <h4>Cooked Meal Inventory Details</h4>
    {% else %}
    <h1>Please Login</h1>

    <form method="post" action="{% url 'FoodBankManage:user_login' %}">
      {% csrf_token %}
      
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Username">

      <label for="password"></label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">

    </form>

    {% endif %}

      
    </div>

    {% if user.is_authenticated %}
    <div class="contai">  
        <form id="contact" name="inventory" action="../foodBankInventrycookAdd/" method="POST">
          {% csrf_token %}
            <fieldset>
              <select name="block_name" id="block" >
                    <option value="{{ blocke }}">{{ blocke }}</option>
                </select>
            </fieldset>
            <fieldset>
                <select name="gram" id="gram">
                    <option value="">Gram Panchayat</option>
                    {% for gram in pancha %}
                    <option value="{{ gram }}">{{ gram }}</option>
                    {% endfor %}
                </select>
            </fieldset>
            <fieldset>
                <input placeholder="Prepared/Recieved Cooked Meal(Government)" name="Cooked_Meal_Government" class="numinput" type="number" min="0" tabindex="1" required autofocus>
            </fieldset>
          <fieldset>
            <input placeholder="Recieved Cooked Meal(From Bhamashah)" name="Cooked_Meal_Bhamashah" class="numinput" type="number" min="0" tabindex="1" required autofocus>
          </fieldset>
          <fieldset>
            <input placeholder="Recieved Cooked Meal(From NGO)" type="number" min="0" class="numinput" name="Cooked_Meal_NGO" tabindex="2" required>
          </fieldset>
          <fieldset>
            <input placeholder="Distributed (Overall Cooked Meal)" name="Distributed_Overall_Cooked_Meal" min="0" class="numinput" type="number" tabindex="4" required>
          </fieldset>
          
          <fieldset>
            <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
          </fieldset>
          
        </form>
      </div>

    {% endif %}
  </div>

  
{% endblock %}

templates/foodinventrydry.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<link rel="stylesheet" href="{% static 'style.css'%}">
  <div class="container">
    <div class="jumbotron">

      {% if user.is_authenticated %}
      <h2>Food Bank Inventory</h2>
      <h4>Dry Food Packet Details</h4>
    {% else %}
    <h1>Please Login</h1>

    <form method="post" action="{% url 'FoodBankManage:user_login' %}">
      {% csrf_token %}
      
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Username">

      <label for="password"></label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">

    </form>

    {% endif %}

      
    </div>

    {% if user.is_authenticated %}
    <div class="contai">  
        <form id="contact" name="inventory" action="../foodBankInventrydryAdd/" method="POST">
          {% csrf_token %}
            <fieldset>
              <select name="block_name" id="block" >
                    <option value="{{ blocke }}">{{ blocke }}</option>
                </select>
            </fieldset>
            <fieldset>
                <select name="gram" id="gram">
                    <option value="">Gram Panchayat</option>
                    {% for gram in pancha %}
                    <option value="{{ gram }}">{{ gram }}</option>
                    {% endfor %}
                </select>
            </fieldset>
            <fieldset>
                <input placeholder="Available" name="available" class="numinput" type="number" min="0" tabindex="1" required autofocus>
            </fieldset>
          <fieldset>
            <input placeholder="Recieved (From Bhamashah)" name="receivedbhama" class="numinput" type="number" min="0" tabindex="1" required autofocus>
          </fieldset>
          <fieldset>
            <input placeholder="Recieved (From Government)" type="number" min="0" class="numinput" name="receivedgovt" tabindex="2" required>
          </fieldset>
          <fieldset>
            <input placeholder="Recieved (From NGO)" name="receivedngo" min="0" class="numinput" type="number" tabindex="4" required>
          </fieldset>
          <fieldset>
            <input placeholder="Distributed" name="distributed" class="numinput" type="number" min="0" tabindex="5" required>
          </fieldset>
          <fieldset>
            <input placeholder="Required" name="Required" type="number" min="0" class="numinput" tabindex="6" required>
          </fieldset>
          <fieldset>
            <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
          </fieldset>
          
        </form>
      </div>

    {% endif %}
  </div>

  
{% endblock %}

templates/foodinventrymid.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<link rel="stylesheet" href="{% static 'style.css'%}">
  <div class="container">
    <div class="jumbotron">

      {% if user.is_authenticated %}
      <h2>Food Bank Inventory</h2>
      <h4>Mid Day Meal Inventory Details</h4>
    {% else %}
    <h1>Please Login</h1>

    <form method="post" action="{% url 'FoodBankManage:user_login' %}">
      {% csrf_token %}
      
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Username">

      <label for="password"></label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">

    </form>

    {% endif %}

      
    </div>

    {% if user.is_authenticated %}
    <div class="contai">  
        <form id="contact" name="inventory" action="../foodBankInventrymidAdd/" method="POST">
          {% csrf_token %}
            <fieldset>
              <select name="block_name" id="block" >
                    <option value="{{ blocke }}">{{ blocke }}</option>
                </select>
            </fieldset>
            <fieldset>
                <select name="gram" id="gram">
                    <option value="">Gram Panchayat</option>
                    {% for gram in pancha %}
                    <option value="{{ gram }}">{{ gram }}</option>
                    {% endfor %}
                </select>
            </fieldset>
            <fieldset>
                <input placeholder="Available (Wheat In Kgs)" name="Available_Wheat_Kgs" class="numinput" type="number" min="0" tabindex="1" required autofocus>
            </fieldset>
          <fieldset>
            <input placeholder="Recieved (Wheat In Kgs)" name="Recieved_Wheat_Kgs" class="numinput" type="number" min="0" tabindex="1" required autofocus>
          </fieldset>
          <fieldset>
            <input placeholder="Distributed (Wheat In Kgs)" type="number" min="0" class="numinput" name="Distributed_Wheat_Kgs" tabindex="2" required>
          </fieldset>
          <fieldset>
            <input placeholder="Required (Wheat In Kgs)" name="Required_Wheat_Kgs" min="0" class="numinput" type="number" tabindex="4" required>
          </fieldset>
          <fieldset>
            <input placeholder="Available (Rice In Kgs)" name="Available_Rice_Kgs" class="numinput" type="number" min="0" tabindex="5" required>
          </fieldset>
          <fieldset>
            <input placeholder="Recieved (Rice In Kgs)" name="Recieved_Rice_Kgs" type="number" min="0" class="numinput" tabindex="6" required>
          </fieldset>
          <fieldset>
            <input placeholder="Distributed (Rice In Kgs)" name="Distributed_Rice_Kgs" type="number" min="0" class="numinput" tabindex="7" required>
          </fieldset>
          <fieldset>
            <input placeholder="Required (Rice In Kgs)" name="Required_Rice_Kgs" type="number" min="0" class="numinput" tabindex="8" required>
          </fieldset>
          <fieldset>
            <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
          </fieldset>
          
        </form>
      </div>

    {% endif %}
  </div>

  
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Django Level Five</h1>
    {% if user.is_authenticated %}
        <h2>Welcome {{ user.username }}!</h2>
    {% else %}
        <h2>Welcome to the site!</h2>
    {% endif %}
  </div>
</div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">

      {% if user.is_authenticated %}
      <h2>Welcome {{ user.username }}!</h2>
    {% else %}

    <div class="log-form">
      <h2 style="color: white;">Login to your account</h2>
      <form method="post" action="{% url 'FoodBankManage:user_login' %}">
        {% csrf_token %}
        <input type="text" name="username" title="username" placeholder="username" />
        <input type="password" name="password" title="username" placeholder="password" />
        <button type="submit" value="Login" class="btn">Login</button>
      </form>
    </div>

      <style>
        .log-form {
  width: 40%;
  min-width: 320px;
  max-width: 475px;
  background: #fff;
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
  -moz-transform: translate(-50%, -50%);
  -o-transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.25);
}
@media (max-width: 40em) {
  .log-form {
    width: 95%;
    position: relative;
    margin: 2.5% auto 0 auto;
    left: 0%;
    -webkit-transform: translate(0%, 0%);
    -moz-transform: translate(0%, 0%);
    -o-transform: translate(0%, 0%);
    -ms-transform: translate(0%, 0%);
    transform: translate(0%, 0%);
  }
}
.log-form form {
  display: block;
  width: 100%;
  padding: 2em;
}
.log-form h2 {
  color: #5d5d5d;
  font-family: 'open sans condensed';
  font-size: 1.35em;
  display: block;
  background: #2a2a2a;
  width: 100%;
  text-transform: uppercase;
  padding: 0.75em 1em 0.75em 1.5em;
  box-shadow: inset 0px 1px 1px rgba(255, 255, 255, 0.05);
  border: 1px solid #1d1d1d;
  margin: 0;
  font-weight: 200;
}
.log-form input {
  display: block;
  margin: auto auto;
  width: 100%;
  margin-bottom: 2em;
  padding: 0.5em 0;
  border: none;
  border-bottom: 1px solid #eaeaea;
  padding-bottom: 1.25em;
  color: #757575;
}
.log-form input:focus {
  outline: none;
}
.log-form .btn {
  display: inline-block;
  background: #1fb5bf;
  border: 1px solid #1ba0a9;
  padding: 0.5em 2em;
  color: white;
  margin-right: 0.5em;
  box-shadow: inset 0px 1px 0px rgba(255, 255, 255, 0.2);
}
.log-form .btn:hover {
  background: #23cad5;
}
.log-form .btn:active {
  background: #1fb5bf;
  box-shadow: inset 0px 1px 1px rgba(0, 0, 0, 0.1);
}
.log-form .btn:focus {
  outline: none;
}
.log-form .forgot {
  color: #33d3de;
  line-height: 0.5em;
  position: relative;
  top: 2.5em;
  text-decoration: none;
  font-size: 0.75em;
  margin: 0;
  padding: 0;
  float: right;
}
.log-form .forgot:hover {
  color: #1ba0a9;
}
      </style>
    {% endif %}

      
  </div>
{% endblock %}

templates/submit.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<link rel="stylesheet" href="{% static 'style.css'%}">
  <div class="container">
    <div class="jumbotron">

      {% if user.is_authenticated %}
      <h2>Food Bank</h2>
      <p>Submitted Successfully!!</p>
    {% else %}
    <h1>Please Login</h1>

    <form method="post" action="{% url 'FoodBankManage:user_login' %}">
      {% csrf_token %}
      
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Username">

      <label for="password"></label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">

    </form>

    {% endif %}

      
</div>
  
{% endblock %}